name: Build macOS

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - 'resources/**'
      - 'neutralino.config.json'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Clean dist folder
        run: rm -rf dist
      
      - name: Install Neutralino CLI
        run: npm install -g @neutralinojs/neu

      - name: Update Neutralino binaries and client
        run: neu update
      
      - name: Build for macOS
        run: neu build --release

      - name: List dist folder contents
        run: ls -R dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MathsBalance-macOS
          path: dist/**/*
          retention-days: 30
          if-no-files-found: error
