name: Build Linux

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - 'resources/**'
      - 'neutralino.config.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Neutralino CLI & Dependencies
        run: |
          npm install -g @neutralinojs/neutralino-cli
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      
      - name: Build for Linux
        run: neu build --release --output-format appimage
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MathsBalance-Linux
          path: dist/MathsBalance/MathsBalance.AppImage
          retention-days: 30
